### ISSUE TITLE
Error when loading image

### ISSUE THREAD

**Issue by maryjis** [ulikoehler/OTR#4]
I run module  python test-otr.py 0110_099.png and get this error

Traceback (most recent call last):
  File "C:/Users/User/Documents/проект по иммунологии/OTR/test-otr.py", line 56, in <module>
    img = runOTR("0110_099.png")
  File "C:/Users/User/Documents/проект по иммунологии/OTR/test-otr.py", line 27, in runOTR
    contour_analyzer.find_corner_clusters()
  File "C:\Users\User\Documents\проект по иммунологии\OTR\TableRecognition.py", line 293, in find_corner_clusters
    distmat = scipy.spatial.distance.cdist(corners, corners, 'euclidean')
  File "C:\Users\User\Anaconda3\lib\site-packages\scipy\spatial\distance.py", line 2369, in cdist
    raise ValueError('XA must be a 2-dimensional array.')
ValueError: XA must be a 2-dimensional array.

**Comment by ulikoehler** [comment]
Thanks for reporting this - I'll take a closer look later this week when I'm back from a business trip. Any chance you could share  0110_099.png so I could test with your data?
