### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by PiotrFerenc** [ulikoehler/OTR#8]
file:
`http://www.nasflmuseum.com/uploads/4/9/5/8/4958573/_7848632_orig.jpg`

python3 test-otr.py test2.jpg 

```

Traceback (most recent call last):
  File "test-otr.py", line 56, in <module>
    img = runOTR(args.infile)
  File "test-otr.py", line 18, in runOTR
    contour_analyzer = TableRecognition.ContourAnalyzer(imgDil)
  File "/home/piotr/OTR/TableRecognition.py", line 76, in __init__
    im2, contours, hierarchy = cv2.findContours(img, cv2.RETR_TREE, cv2.CHAIN_APPROX_TC89_KCOS, **kwargs)
ValueError: not enough values to unpack (expected 3, got 2)
```

Python 3.6.3
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
OpenCV: 3.1.0

**Comment by ulikoehler** [comment]
Thanks for reporting this. Probably I can't take a look until early next week. It seems to fail at a pretty early stage in the process so I believe that some addition preprocessing will be required to the image.

**Comment by PiotrFerenc** [comment]
Which version do you use?

**Comment by traumatic** [comment]
Any news?

**Comment by PiotrFerenc** [comment]
nope

**Comment by jewelcai** [comment]
downgrade your opencv-python or delete the first return value of find_contour()

**Comment by ulikoehler** [comment]
Sorry, could not have a look at this earlier. I will now try to find a portable solution.

**Comment by ulikoehler** [comment]
Could any of you guys test the solution? The fix should be pretty straightforward if I understand the issue correctly, I just don't have any good test data available at the moment.

**Comment by jewelcai** [comment]
> Could any of you guys test the solution? The fix should be pretty straightforward if I understand the issue correctly, I just don't have any good test data available at the moment.

it is acceptable.

**Comment by ulikoehler** [comment]
@jewelcai Thanks for checking! Any suggestions on how to make it better than just acceptable?

**Comment by jewelcai** [comment]
> @jewelcai Thanks for checking! Any suggestions on how to make it better than just acceptable?

haha。 Acceptable means the issue is fixed.

**Comment by PiotrFerenc** [comment]
Any news?

**Comment by ulikoehler** [comment]
@PiotrFerenc
It should be fixed... Can you test?

**Comment by PiotrFerenc** [comment]
![obraz](https://user-images.githubusercontent.com/30370747/61956805-2a4f5500-afbe-11e9-8f73-be7e816462e4.png)

python3-opencv 3.1.0
python3-scipy 0.18.1.1
python3-numpy 1.12

**Comment by ulikoehler** [comment]
@PiotrFerenc Thanks! This seems to happen at a different location than the one I've already fixed for some reason. I have just pushed a commit that should fix that instance as well. Could you pull and test again?
