### ISSUE TITLE
draw contours error

### ISSUE THREAD

**Issue by redflower2017** [ulikoehler/OTR#9]
Traceback (most recent call last):
  File "/home/temp/Desktop/OTR-master/MIME/contour1.py", line 41, in <module>
    contour_analyzer.visualize_contours(img)
  File "/home/temp/Desktop/OTR-master/MIME/TableRecognition.py", line 442, in visualize_contours
    cv2.drawContours(img, self.contours_bbox, -1, (0,255,0), thickness)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/drawing.cpp:2606: error: (-215:Assertion failed) reader.ptr != NULL in function 'cvDrawContours'

is this the opencv version conflict problem ?

**Comment by ulikoehler** [comment]
I think it *might* be that it doesnt recognize any table cells, you could try to
```
print(self.contours_bbox)
```
just before the relevant line.

**Comment by redflower2017** [comment]
[draw_contours_output.txt](https://github.com/ulikoehler/OTR/files/3551021/draw_contours_output.txt)
although it have many None but still have some value in array
